version: '3.8'

services:
  mysql_db:
    build:
      context: db/mysql
      dockerfile: Dockerfile
    container_name: nest_tutorial_mysql_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_nest_network

  mongo_db:
    build:
      context: db/mongo
      dockerfile: Dockerfile
    container_name: nest_tutorial_mongo_database
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dev_nest_network
    restart: always

networks:
  dev_nest_network: {}

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/data/mysql
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/data/mongo