version: '3.8'

services:
  mysql_db:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: nest_tutorial_mysql_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_nest_network

networks:
  dev_nest_network: {}

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/data