# Dockerfile
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=mysql_password
ENV MYSQL_DATABASE=mysql_database
ENV MYSQL_USER=mysql_user
ENV MYSQL_PASSWORD=mysql_password

# Expose the MySQL port
EXPOSE 3306