# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB database_nest_tutorial
ENV POSTGRES_USER user_nest_tutorial
ENV POSTGRES_PASSWORD password_nest_tutorial

# Expose the default PostgreSQL port (5432)
EXPOSE 5432